#!/usr/bin/env bash
# select-location-containers.sh
# Queries Azure for regions that support Azure Container Apps and are available
# to this subscription, presents a numbered menu, and writes the selection to:
#   - .env              (source this for shell commands: source .env)
#   - account.auto.tfvars  (OpenTofu picks this up automatically)
#
# Run this once before starting the lab.  Re-run it to change your region.
#
# Usage:
#   bash select-location-containers.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
TFVARS_FILE="$SCRIPT_DIR/account.auto.tfvars"
TMPDIR_WORK=$(mktemp -d)
trap 'rm -rf "$TMPDIR_WORK"' EXIT

echo ""
echo "Fetching Azure regions that support Azure Container Apps..."
echo ""

# Pull recommended regions with availability zone count
az account list-locations \
    --query "[?metadata.regionCategory=='Recommended' && (metadata.geographyGroup=='US' || metadata.geographyGroup=='Canada' || metadata.geographyGroup=='Mexico')].{name:name, display:displayName, zones:availabilityZoneMappings}" \
    -o json > "$TMPDIR_WORK/locations.json"

# Pull the regions where Azure Container Apps is available (returns display names)
az provider show \
    --namespace Microsoft.App \
    --query "resourceTypes[?resourceType=='containerApps'].locations[]" \
    -o json > "$TMPDIR_WORK/ca_locations.json"

# Build indexed arrays filtered to Container Apps-supported regions only
mapfile -t NAMES < <(python3 -c "
import json
locations = json.load(open('${TMPDIR_WORK}/locations.json'))
ca_raw    = json.load(open('${TMPDIR_WORK}/ca_locations.json'))
ca_set    = {loc.lower().replace(' ', '') for loc in ca_raw}
for r in locations:
    if r.get('displayName', r.get('display', '')).lower().replace(' ', '') in ca_set:
        print(r['name'])
")
mapfile -t DISPLAYS < <(python3 -c "
import json
locations = json.load(open('${TMPDIR_WORK}/locations.json'))
ca_raw    = json.load(open('${TMPDIR_WORK}/ca_locations.json'))
ca_set    = {loc.lower().replace(' ', '') for loc in ca_raw}
for r in locations:
    if r.get('displayName', r.get('display', '')).lower().replace(' ', '') in ca_set:
        print(r.get('displayName', r.get('display', '')))
")
mapfile -t ZONES < <(python3 -c "
import json
locations = json.load(open('${TMPDIR_WORK}/locations.json'))
ca_raw    = json.load(open('${TMPDIR_WORK}/ca_locations.json'))
ca_set    = {loc.lower().replace(' ', '') for loc in ca_raw}
for r in locations:
    if r.get('displayName', r.get('display', '')).lower().replace(' ', '') in ca_set:
        print(len(r.get('zones') or []))
")

# Print numbered menu
printf "\n%-5s %-28s %-35s %s\n" "Num" "Region Name" "Display Name" "AZ Zones"
printf "%-5s %-28s %-35s %s\n"   "---" "-----------" "------------" "--------"
for i in "${!NAMES[@]}"; do
    ZONE_LABEL="${ZONES[$i]} zone(s)"
    [[ "${ZONES[$i]}" == "0" ]] && ZONE_LABEL="no zones"
    printf "%-5s %-28s %-35s %s\n" "$((i+1))" "${NAMES[$i]}" "${DISPLAYS[$i]}" "$ZONE_LABEL"
done

echo ""
read -rp "Enter the number of your preferred region: " SELECTION

# Validate input
if ! [[ "$SELECTION" =~ ^[0-9]+$ ]] || \
   [[ "$SELECTION" -lt 1 ]] || \
   [[ "$SELECTION" -gt "${#NAMES[@]}" ]]; then
    echo "Invalid selection. Exiting."
    exit 1
fi

CHOSEN_NAME="${NAMES[$((SELECTION-1))]}"
CHOSEN_DISPLAY="${DISPLAYS[$((SELECTION-1))]}"
CHOSEN_ZONES="${ZONES[$((SELECTION-1))]}"
SUBSCRIPTION_ID=$(az account show --query id -o tsv)

echo ""
echo "Selected: $CHOSEN_DISPLAY ($CHOSEN_NAME) — ${CHOSEN_ZONES} availability zone(s)"
echo "Subscription: $SUBSCRIPTION_ID"
echo ""

# Write .env for shell use
cat > "$ENV_FILE" << EOF
# Auto-generated by select-location-containers.sh — re-run to change
export LOCATION="$CHOSEN_NAME"
export SUBSCRIPTION_ID="$SUBSCRIPTION_ID"
EOF
echo "Written: $ENV_FILE"

# Write account.auto.tfvars for OpenTofu
mkdir -p "$(dirname "$TFVARS_FILE")"
cat > "$TFVARS_FILE" << EOF
# Auto-generated by select-location-containers.sh — re-run to change
# DO NOT commit this file — it contains your subscription ID
subscription_id = "$SUBSCRIPTION_ID"
location        = "$CHOSEN_NAME"
EOF
echo "Written: $TFVARS_FILE"

echo ""
echo "Next step — load into your current shell:"
echo "  source $ENV_FILE"
echo ""
echo "  LOCATION=$CHOSEN_NAME"
echo "  SUBSCRIPTION_ID=$SUBSCRIPTION_ID"
